name: Bid Window
favicon: null
layout_spectrum: 0.9083334233146161
typography_spectrum: 0.12781005213037133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f8fe'
    - '#7760b2'
    - '#6ecf90'
    - '#e11d31'
    - '#e99a94'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
